name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30.0'

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release
        
      - name: View Build Files
        run: ls build

      - name: Include
        run: ls build/include

      - name: Src
        run: ls build/src
        
      - name: View Release Files
        run: ls build/Release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: build/Release/SolarSystem.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
